### PR TITLE
[MNT] Implemented error boundary

### LINKED ISSUE #95: [ENH] Adopt Error boundary
We should use an error boundary in our app: https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary

TODO:

- [x] If app breaks horribly, show a simple "This should not have happened" page
- [x] include on the page a link to open an issue
- [x] if possible, see if the feedback scriptlet from appzi can be included on this page
- [x] put any interesting learnings about error boundaries into the dev-docs (e.g. link to a site with the interesting info is good enough)

### PR DESCRIPTION
**Pull request by rmanaem**
- Closes #95 

image

**NOTE: If this pull request is to be released, the release label must be applied once the review process is done to avoid the local and remote from going out of sync as a consequence of the `bump version` workflow run**

## Checklist
_This section is for the PR reviewer_

- [x] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see our [Contributing Guidelines](https://neurobagel.org/contributing/CONTRIBUTING#pull-request-guidelines) for more info)_
- [x] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [x] PR links to GitHub issue with mention `Closes #XXXX`
- [x] Tests pass
- [x] Checks pass
- [ ] If the PR changes the participant-level and/or the dataset-level result file, the [`query-tool-results` files](https://github.com/neurobagel/neurobagel_examples/tree/main/query-tool-results) in the  [neurobagel_examples repo](https://github.com/neurobagel/neurobagel_examples/) have been regenerated

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

## Summary by Sourcery

Implement an ErrorBoundary component to enhance error handling in the application by wrapping the main component, ensuring that errors are caught and displayed with a user-friendly message.

New Features:
- Introduce an ErrorBoundary component to handle errors gracefully in the application.

Enhancements:
- Wrap the main application component with the ErrorBoundary to catch and display errors.

### CODE REVIEW

**Comment by rmanaem** [comment]
image

**Review by surchs — COMMENTED** [review]
Thanks @rmanaem, this looks awesome!

:cook:

**Review by surchs — APPROVED** [review]
:cook:

**Comment by surchs** [comment]
Oh, @rmanaem I think we should release off of this PR so we can finally get the synced results files into the deployed app: #389

**Pull request merged**
