### PR TITLE
🔄 synced file(s) with neurobagel/workflows

### PR DESCRIPTION
**Pull request by surchs**
synced local file(s) with [neurobagel/workflows](https://github.com/neurobagel/workflows).

<details>
<summary>Changed files</summary>
<ul>
<li>synced local  <code>.autorc</code> with remote  <code>template_configs/.autorc</code></li><li>synced local  <code>.github/pull_request_template.md</code> with remote  <code>template_prs/auto_release_repo_pr.md</code></li><li>synced local  <code>.github/workflows/build_docker_on_release.yml</code> with remote  <code>template_workflows/auto_release/build_docker_on_release.yml</code></li>
</ul>
</details>

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#8649288772](https://github.com/neurobagel/workflows/actions/runs/8649288772)

### CODE REVIEW

**Comment by alyssadai** [comment]
@neurobagel/dev I would recommend merging this before we make another release b/c it will prevent any bot/`skip-release` PRs from entering the CHANGELOG.

Given that the prettier check is failing, do we want to
- merge w/ failing check
or
- make prettier ignore `.github` first and then merge
?

**Comment by surchs** [comment]
I'd vote to ignore GitHub first and then merge. Let's not get into the habit of ignoring the checks

**Comment by alyssadai** [comment]
- Blocked by https://github.com/neurobagel/query-tool/pull/127 due to failing check

**Comment by alyssadai** [comment]
FYI: e2e test was failing briefly on the [build](https://github.com/neurobagel/query-tool/actions/runs/8676758753/job/23791582954?pr=115) step but a rerun seemed to do the trick. 👀

**Review by alyssadai — APPROVED** [review]

**Pull request merged**
